//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// RokDeBone2.rc で使用
//
#define ID_FILE_LOAD_BF                 0
#define IDOK2                           3
#define IDCANCEL2                       4
#define IDS_PROJNAME                    100
#define IDR_ROKDEBONE2                  101
#define IDS_TB_R                        101
#define IDB_SIGTREEVIEW2                102
#define IDS_TB_T                        102
#define IDR_SIGTREEVIEW2                103
#define IDS_TB_S                        103
#define IDD_SIGEDITDLG                  104
#define IDS_TB_G                        104
#define IDD_OPTDLG                      105
#define IDS_TB_L                        105
#define IDD_MOTPARAMDLG                 106
#define IDS_TB_T2                       106
#define IDB_SIGTREEVIEW                 107
#define IDS_TB_J                        107
#define IDS_TB_ITI                      107
#define IDR_SIGTREEVIEW                 108
#define IDS_TB_FACE                     108
#define IDD_SHDPARAMDLG                 109
#define IDS_TB_LINE                     109
#define IDD_LOADPARAMDLG                110
#define IDS_TB_ZA1                      110
#define IDD_FRAMEOPEDLG                 111
#define IDS_TB_ZA2                      111
#define IDD_MOTSETTINGDLG               112
#define IDS_TB_IKT                      112
#define IDD_JOINTLOCDLG                 113
#define IDS_TB_POINT                    113
#define IDD_NEWJOINTDLG                 114
#define IDS_TB_COLR                     114
#define IDD_WRITEBMPDLG                 115
#define IDS_TB_COLP                     115
#define IDD_INFLUENCEDLG                116
#define IDS_TB_COLB                     116
#define IDD_BGDLG                       117
#define IDS_TB_COLS                     117
#define IDD_LIGHTDLG                    118
#define IDS_TB_COLM                     118
#define IDD_VERSIONDLG                  119
#define IDS_TB_OFC                      119
#define IDS_TB_OFS                      120
#define IDS_TB_OFO                      121
#define IDS_TB_COL                      122
#define IDS_TB_BONE                     123
#define IDS_TB_EI1                      124
#define IDS_TB_EI2                      125
#define IDS_TB_EI3                      126
#define IDS_TB_COLT                     127
#define IDS_TB_TOON1                    128
#define IDS_TB_MO                       129
#define IDS_TB_ZA3                      130
#define IDS_TB_TIMA                     131
#define IDS_TB_SHA                      131
#define IDS_TB_MEMA                     132
#define IDS_TB_4                        132
#define IDS_TB_TEN2                     133
#define IDS_TB_ZA4                      134
#define IDS_TB_GLOW                     135
#define IDS_STRING136                   136
#define IDS_TB_COLPP                    136
#define IDC_SP_UD                       201
#define IDMENU_IKUNDO                   201
#define IDC_SP_ROT                      202
#define IDD_CAMERADLG                   202
#define IDC_SELLOCK_START               202
#define IDC_UD_RESET                    203
#define IDB_PART_IMAGE                  203
#define IDC_SELLOCK_STOP                203
#define IDC_SP_ZOOM                     204
#define IDB_PART_SELECT                 204
#define IDC_SP_TWIST                    204
#define IDC_ROT_RESET                   205
#define IDB_DISP_IMAGE                  205
#define IDC_SELLOCK_NAME                205
#define IDC_ZOOM_RESET                  206
#define IDB_DISP_SELECT                 206
#define IDC_SP_BONENUM                  206
#define IDC_RADIO_BONE1                 207
#define IDB_BONE_IMAGE                  207
#define IDC_SP_RAD2                     207
#define IDC_TEX_BONENUM                 207
#define IDC_RADIO_BONE2                 208
#define IDB_BONE_SELECT                 208
#define IDC_RAD2_RESET                  208
#define IDC_RESET_ROT                   208
#define IDC_RESET_MV                    209
#define IDC_TREE_MOT                    210
#define IDR_DUMMYMENU                   210
#define IDD_MQODLG                      210
#define IDR_DLGMENU                     211
#define IDD_DISPSWITCHDLG               211
#define IDC_SL_MP                       212
#define IDC_EDIT_MULT                   212
#define IDMENU_REVIKUNDO                212
#define IDC_DELETE                      213
#define IDD_TEXSETTINGDLG               213
#define IDC_ADD                         214
#define IDD_LDSIG                       214
#define IDC_SL_MP2                      214
#define IDC_SL_RANGE                    214
#define IDC_FRAMEPASTE                  215
#define IDC_ADD2                        215
#define IDD_WRITEBFDLG                  215
#define IDC_FRAMECOPY                   216
#define IDC_DELETE2                     216
#define IDD_FRAMECOPYDLG                216
#define IDC_PREVIEW                     217
#define IDD_PASTETYPEDLG                217
#define IDC_SL_ROTX                     218
#define IDC_FRAMEPASTE2                 218
#define IDC_SL_ROTY                     219
#define IDC_SP_ROTRAD                   219
#define IDC_SL_ROTZ                     220
#define IDC_SP_ROTX                     221
#define IDD_PARSDLG                     221
#define IDC_SP_ROTY                     222
#define ID_222                          222
#define IDC_SP_ROTZ                     223
#define IDD_AXISDLG                     223
#define IDC_MVX                         224
#define IDC_TEX_RAD                     224
#define IDD_MOTDLG                      224
#define IDC_MVY                         225
#define IDD_VIKDLG                      225
#define IDC_MVZ                         226
#define IDC_MV_SET                      227
#define IDC_MVZ2                        227
#define IDC_STATIC1                     228
#define IDC_CHECK_SKINNING              228
#define IDC_SWITCH13                    228
#define IDC_UNSELCOL                    228
#define IDC_SELCOL_LINE                 228
#define IDC_TEXT_AMBIENT                228
#define IDC_STATIC2                     229
#define IDC_ALL_NOSKINNING              229
#define IDC_SELCOL_LINE2                229
#define IDC_SELCOL_POINT                229
#define IDC_TEXT_DIFFUSE                229
#define IDC_TEX_ROTX                    230
#define IDC_ALL_SKINNING                230
#define IDC_TEXT_SPECULAR               230
#define IDC_STATIC3                     231
#define IDC_DISPSWITCHNO                231
#define IDC_TEX_ROTY                    232
#define IDC_COMBO_NO                    232
#define IDC_TEXT_SPECULAR2              232
#define IDC_STATIC4                     233
#define IDC_SWITCHON                    233
#define IDC_TEX_ROTZ                    234
#define IDC_SWITCHOFF                   234
#define IDC_STATIC5                     235
#define IDC_FRAMENO                     235
#define IDC_STATIC6                     236
#define IDC_SWITCH1                     236
#define IDC_STATIC7                     237
#define IDC_SWITCH2                     237
#define IDC_STATIC8                     238
#define IDC_SWITCH3                     238
#define IDC_STATIC9                     239
#define IDC_SWITCH4                     239
#define IDC_TEX_NAME                    240
#define IDC_SWITCH5                     240
#define IDC_TEX_CURRENT                 241
#define IDC_SWITCH6                     241
#define IDC_SWITCH7                     242
#define IDC_MP                          243
#define IDC_SWITCH8                     243
#define IDR_R_MENU                      243
#define IDC_SHDNAME                     244
#define IDC_SWITCH9                     244
#define IDC_SW                          244
#define IDC_MP2                         244
#define IDC_RANGE                       244
#define IDC_SERIALNO                    245
#define IDC_SWITCH10                    245
#define IDC_SHDTYPE                     246
#define IDC_SWITCH11                    246
#define IDC_DEPTH                       247
#define IDC_SWITCH12                    247
#define ID_RMENU_247                    247
#define IDC_CLOCKWISE                   248
#define IDC_SWITCH14                    248
#define IDC_ALPHA                       249
#define IDC_SWITCH15                    249
#define ID_RMENU_249                    249
#define IDC_TEXNAME                     250
#define IDC_DISPSWITCH                  250
#define IDC_TEXREF                      251
#define IDC_NAME_ADD                    251
#define IDD_BONELINEDLG                 251
#define IDC_TRANSPARENT                 252
#define IDC_NAME_DEL                    252
#define IDR_ACCELERATOR1                252
#define IDC_NAME_UP                     253
#define IDD_WRITEMQODLG                 253
#define IDC_TEXRULE                     254
#define IDC_NAME_DOWN                   254
#define IDC_TEXREPX                     255
#define IDC_COMBO_TEXRULE               255
#define IDB_BITMAP1                     255
#define IDC_TEXREPY                     256
#define IDC_TEXREPU                     256
#define IDB_BITMAP2                     256
#define IDC_UANIME                      257
#define IDC_TEXREPV                     257
#define IDD_LDBVH                       257
#define IDC_VANIME                      258
#define IDC_UANIM                       258
#define IDD_WRITEIM2Dlg                 258
#define IDC_REF_DIFFUSE                 259
#define IDC_VANIM                       259
#define IDC_DISP_DIFFUSE                260
#define IDD_DIALOG1                     260
#define IDD_MIKOBLENDDLG                260
#define IDC_RADIO_POLY1                 261
#define IDC_TEXTURE                     261
#define IDD_DIALOG2                     261
#define IDD_LOADNAMEDLG                 261
#define IDC_RADIO_POLY2                 262
#define IDC_COMBO_ANIM_REP              262
#define IDD_LDSIG1                      262
#define IDD_LDGROUNDDLG                 262
#define IDC_COLDIF                      262
#define IDC_REF_AMBIENT                 263
#define IDC_ANIM_STEP                   263
#define IDC_TEXTURE3                    263
#define IDC_COLSPC                      263
#define IDC_SL_SPECULAR                 264
#define IDC_RADIO_NORMAL                264
#define IDC_TEX_DIFFUSE                 265
#define IDC_RADIO_ANIM                  265
#define IDC_TEX_AMBIENT                 266
#define IDC_RADIO_MULTI                 266
#define IDC_DISP_AMBIENT                267
#define IDC_LIST_TEXNAME                267
#define IDD_IKTARGETDLG                 267
#define IDC_TEX_SPECULAR                268
#define IDC_NOTUSE                      269
#define IDD_FRAMESHIFTDLG               269
#define IDC_MULTIPLE                    270
#define IDC_RADIO_FULLPATH              270
#define IDD_FRAMEOPEDLG1                270
#define IDD_FRAMEPASTEDLG               270
#define IDC_SWAPXZ                      271
#define IDC_RADIO_ONLYNAME              271
#define IDD_WRITEQUADLG                 271
#define IDC_CENTERX                     272
#define IDC_SIGNAME                     272
#define IDD_WRITEQUADLG1                272
#define IDD_IMPORTQUADLG                272
#define IDC_CENTERZ                     273
#define IDC_REF                         273
#define IDC_DIV_COLOR                   274
#define IDC_MULT                        274
#define IDR_SIG2                        274
#define IDC_DIV_GROUP                   275
#define IDC_RADIO_NOALPHA               275
#define IDC_INVZ                        276
#define IDC_RADIO_WITHALPHA             276
#define IDB_BITMAP6                     276
#define IDC_FRAMEDEL                    277
#define IDC_RADIO_WITHTRANS             277
#define IDD_ITIMODEDLG                  277
#define IDC_PARAMSET                    278
#define IDD_ITIDLG                      278
#define IDC_TEXT                        279
#define IDC_CHECK1                      279
#define IDC_LIST1                       280
#define IDD_SETCOLDLG                   280
#define IDC_CHECK2                      280
#define IDC_CHECK2_1                    280
#define IDC_IGNLIM                      280
#define IDC_MQO                         280
#define IDC_MV                          280
#define IDC_CHKLAST                     280
#define IDC_CHILDJOINT                  280
#define IDC_LIST2                       281
#define IDD_SETCOL2DLG                  281
#define IDC_CHECK4                      281
#define IDC_CHECK2_2                    281
#define IDC_CHKINV                      282
#define IDD_DIALOG3                     282
#define IDD_MOUSEOPTDLG                 282
#define IDC_CHECK8                      282
#define IDC_CHECK2_3                    282
#define IDC_ELEMLIST                    282
#define IDC_TEXT_EYEY                   283
#define IDD_DIALOG4                     283
#define IDD_CREATEBONEDLG               283
#define IDC_CHECK16                     283
#define IDC_CHECK2_4                    283
#define IDC_TEXT_RAD                    284
#define IDC_SLIDER1                     284
#define IDC_CHECK32                     284
#define IDC_CHECK2_5                    284
#define IDC_TEXT_DIST                   285
#define IDC_FOVTEXT                     285
#define IDD_SELSCOPEDLG                 285
#define IDC_CHECK64                     285
#define IDC_CHECK2_6                    285
#define IDC_TEXT_RAD2                   286
#define IDC_RADIO_PARS1                 286
#define IDD_INFSCOPEDLG                 286
#define IDC_CHECK128                    286
#define IDC_CHECK2_7                    286
#define IDC_RADIO_ORTHO1                287
#define IDD_PAINTDLG                    287
#define IDC_CHECK256                    287
#define IDC_CHECK2_8                    287
#define IDC_RADIO_GROUND1               288
#define IDD_DIALOG5                     288
#define IDD_ONEORALLDLG                 288
#define IDC_CHECK512                    288
#define IDC_CHECK2_9                    288
#define IDC_EDIT_ORTHOSIZE              289
#define IDC_CHECK1024                   289
#define IDC_CHECK2_10                   289
#define IDC_RADIO_GROUND2               290
#define IDI_ICON2                       290
#define IDC_CHECK2048                   290
#define IDC_CHECK2_11                   290
#define IDC_RANGEX                      291
#define IDD_DIALOG6                     291
#define IDD_EDITINF                     291
#define IDC_CHECK4096                   291
#define IDC_CHECK2_12                   291
#define IDC_RANGEY                      292
#define IDC_SL_SIZE                     292
#define IDC_CHECK8192                   292
#define IDC_CHECK2_13                   292
#define IDC_RANGEZ                      293
#define IDC_TEXT_SIZE                   293
#define IDR_RCDATA1                     293
#define IDC_CHECK16384                  293
#define IDC_CHECK2_14                   293
#define IDC_TOTALFRAME                  294
#define IDC_RADIO_UNDO1                 294
#define IDD_DIALOG7                     294
#define IDD_WRITEXFILEDLG               294
#define IDC_CHECK129                    294
#define IDC_CHECK32768                  294
#define IDC_CHECK2_15                   294
#define IDC_RADIO1                      295
#define IDC_RADIO_UNDO0                 295
#define IDD_TOON1DLG                    295
#define IDC_CHECK2_21                   295
#define IDC_RADIO2                      296
#define IDC_BONEDISP                    296
#define IDD_LDSIG2                      296
#define IDD_LDFBX                       296
#define IDC_CHECK2_22                   296
#define IDC_VIEW                        297
#define IDD_LDFBX1                      297
#define IDD_LDX                         297
#define IDC_CHECK2_23                   297
#define IDC_RADIO3                      298
#define IDC_SL_XZ                       298
#define IDC_R_MOTINV                    298
#define IDC_MOVE_ABSOLUTE               298
#define IDC_RADIO_DEL                   298
#define IDD_DIALOG8                     298
#define IDD_MOTCHANGEDLG                298
#define IDC_CHECK2_24                   298
#define IDC_NAME                        299
#define IDC_SL_Y                        299
#define IDR_MENU1                       299
#define IDR_MCR_MENU                    299
#define IDC_CHECK2_25                   299
#define IDC_TEXT_STATUS                 300
#define IDC_TEXT_SL_XZ                  300
#define IDD_MCPARENTDLG                 300
#define IDC_CHECK2_26                   300
#define IDC_TEXT_TARGET                 301
#define IDC_TEXT_SL_Y                   301
#define IDD_DIALOG9                     301
#define IDD_MCCHILDDLG                  301
#define IDC_CHECK2_27                   301
#define IDC_SP_TARGET                   302
#define IDC_RADIO_VERT                  302
#define IDD_DIALOG10                    302
#define IDD_SAVEMADLG                   302
#define IDD_WRITEMAFDLG                 302
#define IDC_CHECK2_28                   302
#define IDC_TARGET_RESET                303
#define IDC_RADIO_CUSTOM                303
#define IDD_KFPARAMDLG                  303
#define IDC_CHECK2_29                   303
#define IDC_SP_MP                       304
#define IDC_RADIO_CROSS                 304
#define IDC_CHECK2_30                   304
#define IDC_CHECK_COM_2_29              304
#define IDC_STOP                        305
#define IDC_TAB1                        305
#define IDD_DIALOG11                    305
#define IDD_LDQUADLG                    305
#define IDC_ALLDELETE                   306
#define IDC_TEXT_SELNAME                306
#define IDD_DIALOG12                    306
#define IDD_OVERWRITEDLG                306
#define IDC_EDITX                       307
#define IDC_ALLDELETE2                  307
#define IDC_TEXT_CURX                   307
#define IDD_DIALOG13                    307
#define IDD_EXTSIGDLG                   307
#define IDC_EDITY                       308
#define IDC_TEXT_CURY                   308
#define IDD_MATERIALDLG                 308
#define IDC_EDITZ                       309
#define IDC_TEXT_CURZ                   309
#define IDD_DIALOG14                    309
#define IDD_NORMALMAP                   309
#define IDC_APPLY                       310
#define IDC_EDIT_DIV                    310
#define IDD_BONEPROPDLG                 310
#define IDC_TEXT_NAME                   311
#define IDC_EDIT_TX                     311
#define IDD_CHKOWDLG                    311
#define IDC_EDIT_NUM                    312
#define IDC_EDIT_TY                     312
#define IDD_DIALOG15                    312
#define IDD_LDMKM                       312
#define IDC_PREFIX                      313
#define IDC_EDIT_TZ                     313
#define IDD_MOTPARAMDLG1                313
#define IDD_TEXKEYDLG                   313
#define IDR_MENU2                       313
#define IDR_TEXMENU                     313
#define IDC_STARTFRAME                  314
#define IDC_START_IK                    314
#define IDD_DSKEYDLG                    314
#define IDR_MENU3                       314
#define IDR_DSMENU                      314
#define IDC_ENDFRAME                    315
#define IDC_STOP_IK                     315
#define IDD_SHADOWDLG                   315
#define IDC_START_SHIFTIK               316
#define IDD_4DLG                        316
#define IDC_NOTRANSIK                   317
#define IDD_CREATEKEYDLG                317
#define IDD_DIALOG16                    318
#define IDD_GRAPHDLG                    318
#define IDR_MENU4                       319
#define IDR_FUMENU                      319
#define IDC_TREE1                       320
#define IDD_DIALOG17                    320
#define IDD_EDITLISTINF                 320
#define IDC_NAME1                       321
#define IDD_DIALOG18                    321
#define IDD_MFOLDERDLG                  321
#define IDC_REF1                        322
#define IDC_IKSKIP                      322
#define IDD_TEXKEYDLG1                  322
#define IDD_MORPHKEYDLG                 322
#define IDC_NAME2                       323
#define IDC_RESET_SC                    323
#define IDD_DIALOG19                    323
#define IDD_GLOWVIEWDLG                 323
#define IDC_REF2                        324
#define IDC_RADIO_MODEJOINT             324
#define IDD_DIALOG20                    324
#define IDD_SYMBONEDLG                  324
#define IDC_MVU                         325
#define IDC_RADIO_MODEOPE               325
#define IDD_TOON0DLG                    325
#define IDC_MVV                         326
#define IDC_COMBO1                      326
#define IDC_COMBO_LEVEL                 326
#define IDC_COMBO_FPS                   326
#define IDC_COMBO_IKLEVEL               326
#define IDC_COMBO_OBJECT                326
#define IDC_COMBO_NAME                  326
#define IDC_COMBO_COMMONID              326
#define IDD_CAMERAKEYDLG                326
#define IDC_REF_SELCOL                  327
#define IDD_GPAKEYDLG                   327
#define IDC_COLORREF                    328
#define IDC_REF_UNSELCOL                328
#define IDD_MOEKEYDLG                   328
#define IDC_COLOR                       329
#define IDC_SELCOL                      329
#define IDD_SOUNDDLG                    329
#define IDC_NUMPRIM                     330
#define IDC_RADIO_NOTDISP               330
#define IDD_MOEKEYDLG1                  330
#define IDD_SNDKEYDLG                   330
#define IDC_SL_ALPHA                    331
#define IDC_RADIO                       331
#define IDC_RADIO_DODISP                331
#define IDD_SYNCDLG                     331
#define IDC_SL_BETA                     332
#define IDC_CHECK_CHILD                 332
#define IDD_MOTSETTINGDLG1              332
#define IDD_SNDSETTINGDLG               332
#define IDC_TEXT_ALPHA                  333
#define IDD_ALPKEYDLG                   333
#define IDC_TEXT_BETA                   334
#define IDC_SAVE_F5                     334
#define IDD_EDITINF1                    334
#define IDD_EDITALP                     334
#define IDC_TEXT_VEC                    335
#define IDC_SAVE_F6                     335
#define IDD_WRITEBLDDLG                 335
#define IDC_SAVE_F7                     336
#define IDD_LDSIG3                      336
#define IDD_LDESI                       336
#define IDC_BUTTON5                     337
#define IDC_SAVE_F8                     337
#define IDC_UNSELPOINT                  337
#define IDC_ERA                         337
#define IDC_CHANGENAME                  337
#define IDC_AFTFRAME                    337
#define IDC_ALLOFF                      337
#define IDC_CREATEKEYALL                337
#define IDC_ONE                         337
#define IDC_COPY                        337
#define IDC_ADDLIST                     337
#define IDC_SNDSYNC                     337
#define IDC_GPA                         337
#define IDD_LDESI1                      337
#define IDD_LDEQU                       337
#define IDC_EDIT_HEAD                   338
#define IDC_BUTTON19                    338
#define IDC_PASTE                       338
#define IDC_DELLIST                     338
#define IDD_SPCTRLDLG                   338
#define IDC_BUTTON1                     339
#define IDC_REF_HEAD                    339
#define IDC_REF_BVH                     339
#define IDC_REF_IM2                     339
#define IDC_NEXTMP                      339
#define IDC_BEFORE_MP                   339
#define IDD_DIALOG21                    339
#define IDD_SELBONEDLG                  339
#define IDC_RADIO_ALL                   340
#define IDC_ADDNOTLIST                  340
#define IDC_DELSET                      340
#define IDD_DIALOG22                    340
#define IDD_SELRTSDLG                   340
#define IDC_RADIO_KEY                   341
#define IDC_DELNOTLIST                  341
#define IDC_UPSET                       341
#define IDD_CONVSETDLG                  341
#define IDC_EDIT1                       342
#define IDC_EDIT_BVH                    342
#define IDC_EDIT_BONEFILE               342
#define IDC_EDIT_IM2NAME                342
#define IDC_EDIT_MOTJUMP                342
#define IDC_EDIT_IKCNT                  342
#define IDC_EDIT_SELSTART               342
#define IDC_EDIT_START                  342
#define IDC_EDIT_NAME                   342
#define IDC_POINTSIZE                   342
#define IDC_POSX                        342
#define IDD_SETCHKDLG                   342
#define IDC_CHECK_MOTONLY               343
#define IDC_POSY                        343
#define IDC_TARY                        343
#define IDC_RZ                          343
#define IDC_ADDELEM                     343
#define IDC_DOWNSET                     343
#define IDD_DIALOG23                    343
#define IDD_OPTARGETDLG                 343
#define IDC_EDIT_MQONAME                344
#define IDC_EDIT6                       344
#define IDC_POSZ                        344
#define IDC_TARZ                        344
#define IDC_CENX                        344
#define IDC_BUTTON14                    344
#define IDC_DELELEM                     344
#define IDC_ADDSOUND                    344
#define IDC_ZEROS                       344
#define IDD_MOTCUTDLG                   344
#define IDC_REF_MQONAME                 345
#define IDC_DEG                         345
#define IDC_DELSOUND                    345
#define IDC_ZEROS2                      345
#define IDC_ZEROE                       345
#define IDD_DIALOG24                    345
#define IDD_MABIKIDLG                   345
#define IDC_EDIT_BONNAME                346
#define IDC_PY                          346
#define IDC_UPSOUND                     346
#define IDI_ICON1                       346
#define IDC_REF_BONNAME                 347
#define IDC_PZ                          347
#define IDC_BUTTON18                    347
#define IDC_DOWNSOUND                   347
#define IDD_INFODLG                     347
#define IDC_EDIT2                       348
#define IDC_EDIT_X                      348
#define IDC_EDIT_SELEND                 348
#define IDC_EDIT_END                    348
#define IDC_EDIT_QUASTART               348
#define IDC_MOTNAME                     348
#define IDC_INT0                        348
#define IDC_MULTQUA                     348
#define IDC_NMAP                        348
#define IDC_INITNAME                    348
#define IDC_FORBIDID                    348
#define IDC_BIAS                        348
#define IDC_FIXY                        348
#define IDC_GLOWMULT_G                  348
#define IDC_DIST                        348
#define IDC_DIR                         348
#define IDC_HAKU                        348
#define IDC_SIGMULT                     348
#define IDC_SELEND                      348
#define IDC_EDITRANGE                   348
#define IDD_DIALOG25                    348
#define IDD_FILTERDLG                   348
#define IDC_CHECK_OUTBONE               349
#define IDC_INT1                        349
#define IDC_UPX                         349
#define IDC_RY                          349
#define IDC_GROUNDMULT                  349
#define IDD_DIALOG26                    349
#define IDD_MULTICAPDLG                 349
#define IDC_CHECK_OUTBF                 350
#define IDC_INT2                        350
#define IDC_NEAR                        350
#define IDC_CENY                        350
#define IDD_DIALOG27                    350
#define IDD_TARGETBONE                  350
#define IDC_BUTTON2                     351
#define IDC_REF_BONEFILE                351
#define IDC_NEXT_MP                     351
#define IDC_SELLINE                     351
#define IDC_FACE                        351
#define IDC_REFDIFFUSE                  351
#define IDC_EXC                         351
#define IDC_AFTER                       351
#define IDC_INT3                        351
#define IDC_CAMMOVE                     351
#define IDC_REFNMAP                     351
#define IDC_ALLNO                       351
#define IDC_REFINITNAME                 351
#define IDC_DELFORBID                   351
#define IDC_DEL                         351
#define IDC_REFDIR                      351
#define IDC_APPLYDIR                    351
#define IDC_APPLYHAKU                   351
#define IDD_SYMBONEDLG1                 351
#define IDD_SYMJPOSDLG                  351
#define IDC_RADIO_FORSIG                352
#define IDC_REFSPECULAR                 352
#define IDC_INT4                        352
#define IDC_FAR                         352
#define IDC_REFBGM                      352
#define IDC_APPLYSEC                    352
#define IDD_LDSIG4                      352
#define IDD_WRITEFBXDLG                 352
#define IDC_RADIO_FORMQO                353
#define IDC_REFAMBIENT                  353
#define IDC_INT5                        353
#define IDC_FOV                         353
#define IDC_REFSOUND                    353
#define IDC_APPLYSEC2                   353
#define IDC_APPLYFRAME                  353
#define IDD_DIALOG28                    353
#define IDD_REGISTDLG                   353
#define IDC_RADIO_RDB2                  354
#define IDC_REFEMISSIVE                 354
#define IDC_INT6                        354
#define IDC_UPY                         354
#define IDC_RADIO_MIKO                  355
#define IDC_INT7                        355
#define IDC_UPZ                         355
#define IDC_RADIO_FPS60                 356
#define IDC_DOUBLE0                     356
#define IDC_RADIO_FPS30                 357
#define IDC_DOUBLE1                     357
#define IDC_RADIO_SKINNING              358
#define IDC_DOUBLE2                     358
#define IDC_RADIO_MIX                   359
#define IDC_DOUBLE3                     359
#define IDC_COMBO2                      360
#define IDC_COMBO_MOTSTEP               360
#define IDC_DOUBLE4                     360
#define IDC_COMBO_BRUSH                 360
#define IDC_COMBO_MODE                  360
#define IDC_COMBOG                      360
#define IDC_COMBOLIST                   360
#define IDC_COMBOBGM                    360
#define IDC_COMBO_RANGE                 360
#define IDC_FILTERSIZE                  360
#define IDC_TEXT_COL                    361
#define IDC_DOUBLE5                     361
#define IDC_COMBONOTLIST                361
#define IDC_QUANAME                     362
#define IDC_DOUBLE6                     362
#define IDC_IM2NAME                     363
#define IDC_DOUBLE7                     363
#define IDC_BONNAME                     364
#define IDC_RADIO_FK                    365
#define IDC_RADIO_IK                    366
#define IDC_RADIO_MOTSTOP               367
#define IDC_RADIO_MOTREP                368
#define IDC_RADIO_MOTINV                369
#define IDC_RADIO_MOTJUMP               370
#define IDC_R_MOTSTOP                   370
#define IDC_RADIO_SQUAD2                371
#define IDC_R_MOTREP                    371
#define IDC_RADIO_SLERP2                372
#define IDC_R_MOTJUMP                   372
#define IDC_R_SQUAD2                    373
#define IDC_RADIO6                      374
#define IDC_R_SLERP2                    374
#define IDC_DODGE                       374
#define IDC_CHECK_IKT                   375
#define IDC_TEXT_JOINTLOC               376
#define IDC_TEXT_JOINTNAME              377
#define IDC_EDIT_Y                      378
#define IDC_EDIT4                       379
#define IDC_EDIT_Z                      379
#define IDC_RSTEP                       379
#define IDC_SOUND                       379
#define IDC_END                         379
#define IDC_R_BM_ON                     379
#define IDC_FRAMESHIFT                  380
#define IDC_DEGSTEP                     380
#define IDC_R_BM_OFF                    380
#define IDC_BUTTON4                     381
#define IDC_CREATEKEY                   381
#define IDC_JOINT                       381
#define IDC_FILELOAD                    381
#define IDC_SUB                         381
#define IDC_BEFFRAME                    381
#define IDC_APPLYALPHA                  381
#define IDC_EDIT_Z3                     381
#define IDC_CRE1                        381
#define IDC_PLAY                        381
#define IDC_CAM                         381
#define IDC_RADIO_IKT_ON                381
#define IDC_RADIO4                      382
#define IDC_OVERLAY                     382
#define IDC_CRE2                        382
#define IDC_RADIO_IKT_OFF               382
#define IDC_TREESHIFT                   383
#define IDC_CRE3                        383
#define IDC_EDIT3                       384
#define IDC_EDIT_SHIFT                  384
#define IDC_EDIT_QUAEND                 384
#define IDC_PARENT                      384
#define IDC_HPARAM                      384
#define IDC_GLOWMULT_B                  384
#define IDC_DEL1                        384
#define IDC_BGM                         384
#define IDC_SEC                         384
#define IDC_RADIO_CURFRAME              385
#define IDC_DEL2                        385
#define IDC_RX                          385
#define IDC_FRAME                       385
#define IDC_RADIO_NUMQUA                385
#define IDC_RADIO_SELECT                386
#define IDC_DEL3                        386
#define IDC_RAYY                        386
#define IDC_RADIO_NAMEQUA               386
#define IDC_CHECK_CREATE                387
#define IDC_RAYLENG                     387
#define IDC_EDIT_SPACE                  388
#define IDC_EDIT11                      388
#define IDC_OFFSETY                     388
#define IDC_UNSELCOL_LINE               389
#define IDC_CENZ                        389
#define IDC_UNSELCOL_POINT              390
#define IDC_BUTTON3                     390
#define IDC_PART                        390
#define IDC_PALETTE1                    390
#define IDC_REFCOL                      390
#define IDC_CAMZOOM                     390
#define IDC_ALLON                       390
#define IDC_FRAMECOPYONE                390
#define IDC_ZERO                        390
#define IDC_SELHEN                      390
#define IDC_CALC                        390
#define IDC_ALLDEL                      390
#define IDC_JUMP                        390
#define IDC_PALETTE2                    391
#define IDC_SEL1                        391
#define IDC_PALETTE3                    392
#define IDC_SEL2                        392
#define IDC_COMBOBOXEX1                 393
#define IDC_PALETTE4                    393
#define IDC_SEL3                        393
#define IDC_UNSELLINE                   394
#define IDC_PALETTE5                    394
#define IDC_SELKAE                      394
#define IDC_BUTTON6                     395
#define IDC_SELPOINT                    395
#define IDC_PALETTE6                    395
#define IDC_DEF                         395
#define IDC_FRAMECOPYALL                395
#define IDC_ALLZERO                     395
#define IDC_APPLYDIST                   395
#define IDC_DOROT                       395
#define IDC_APPLYBPM                    395
#define IDC_MODE_INIT                   396
#define IDC_PALETTE7                    396
#define IDC_EDITCAM                     396
#define IDC_MODE_NOTINIT                397
#define IDC_PALETTE8                    397
#define IDC_MOVE_RELATIVE               398
#define IDC_PALETTE9                    398
#define IDC_EDITCAM2                    398
#define IDC_EDITSW                      398
#define IDC_VERT                        399
#define IDC_PALETTE10                   399
#define IDC_SCREEN                      400
#define IDC_PALETTE11                   400
#define IDC_ML_ROT                      400
#define IDC_RADIO5                      401
#define IDC_HARDLIGHT                   401
#define IDC_PALETTE12                   401
#define IDC_ML_MOVE                     401
#define IDC_INVERSE                     402
#define IDC_PALETTE13                   402
#define IDC_ML_NONE                     402
#define IDC_VDIFFUSE                    403
#define IDC_MR_ROT                      403
#define IDC_VSPECULAR                   404
#define IDC_MR_MOVE                     404
#define IDC_VAMBIENT                    405
#define IDC_MR_NONE                     405
#define IDC_VEMISSIVE                   406
#define IDC_MW_TWIST                    406
#define IDC_POWER                       407
#define IDC_MW_DIST                     407
#define IDC_SL_POWER                    408
#define IDC_MW_NONE                     408
#define IDC_RADIO_SET                   409
#define IDC_RADIO_SPOIT                 410
#define IDC_PALETTE14                   411
#define IDC_RADIO_W2P                   411
#define IDC_RADIO_P2W                   412
#define IDC_PALETTE15                   412
#define IDC_UNDO                        413
#define IDC_PNAME                       414
#define IDC_PNAME1                      414
#define IDC_PNAME2                      415
#define IDC_PNAME3                      416
#define IDC_PNAME4                      417
#define IDC_PNAME5                      418
#define IDC_PNAME6                      419
#define IDC_PNAME7                      420
#define IDC_PNAME8                      421
#define IDC_PNAME9                      422
#define IDC_PNAME10                     423
#define IDC_PNAME11                     424
#define IDC_PNAME12                     425
#define IDC_PNAME13                     426
#define IDC_PNAME14                     427
#define IDC_PNAME15                     428
#define IDC_PNAME16                     429
#define IDC_PALETTE16                   430
#define IDC_FILESAVE                    431
#define IDC_RADIO_NAME                  432
#define IDC_DIFFUSE                     433
#define IDC_SPECULAR                    434
#define IDC_AMBIENT                     435
#define IDC_ANIMATE3                    436
#define IDC_EMISSIVE                    436
#define IDC_DIFFUSE2                    436
#define IDC_CHECK_TEX                   437
#define IDC_MOUSEDLG                    438
#define IDC_RADIO_CREATE                442
#define IDC_RADIO_POS                   443
#define IDC_SETNAME                     444
#define IDC_DELBONE                     445
#define IDC_LIST3                       447
#define IDC_DISPNAME                    448
#define IDC_SELDISP                     449
#define IDC_TREE2                       450
#define IDC_UP                          450
#define IDC_CREATE                      451
#define IDC_DOWN                        451
#define IDC_RADIO_MVALL                 452
#define IDC_RADIO_MVVERT                453
#define IDC_SLIDER_BONE                 454
#define IDC_SLIDER_VERT                 455
#define IDC_SLIDER_HOR                  456
#define IDC_ANIMATE1                    457
#define IDC_COL                         457
#define IDC_EDGECOL0                    457
#define IDC_SLIDER_BONE2                458
#define IDC_SLIDER_ALL                  458
#define IDC_NOR                         460
#define IDC_SL_PER                      461
#define IDC_PER                         462
#define IDC_DISPINF                     463
#define IDC_CHK_NORM                    464
#define IDC_ALLNORM                     465
#define IDC_NORM                        465
#define IDC_BUTTON8                     466
#define IDC_NEWROT                      466
#define IDC_VPROJ                       466
#define IDC_SND                         466
#define IDC_BUTTON9                     467
#define IDC_DISPINFSET                  467
#define IDC_OLDROT                      467
#define IDC_VPROJ2                      467
#define IDC_VORTHO                      467
#define IDC_RADIO_ONE                   470
#define IDC_SYMX                        472
#define IDC_SYMY                        473
#define IDC_SYMZ                        474
#define IDC_                            475
#define IDC_SYMDIST                     475
#define IDC_RADIO7                      476
#define IDC_BONENAME                    477
#define IDC_KIND                        478
#define IDC_VAL                         479
#define IDD_WRITEXDLG                   480
#define IDC_CONVFACE                    481
#define IDC_XNAME                       482
#define IDC_REFX                        483
#define IDC_SLDARK                      484
#define IDC_DARK                        485
#define IDC_SLBRIGHT                    486
#define IDC_BRIGHT                      487
#define IDC_SLDARKDEG                   488
#define IDC_SLDARKDEG2                  489
#define IDC_SLBRIGHTDEG                 489
#define IDC_TEXT_DARKDEG                490
#define IDC_TEXT_BRIGHTDEG              491
#define IDC_BEFORE                      492
#define IDC_MNAME                       493
#define IDC_FNAME                       494
#define IDC_RADIO_ALW                   495
#define IDC_RADIO_FIX                   496
#define IDC_FIXFRAME                    497
#define IDC_CHECK_IDLING                498
#define IDC_JUMPTO                      499
#define IDC_MAFNAME                     500
#define IDC_RADIO_WRAP                  500
#define IDC_REFPARENT                   501
#define IDC_RADIO_NOLIMIT               501
#define IDC_RADIO_NEW                   502
#define IDC_RADIO_OLD                   503
#define IDC_MFRAME                      504
#define IDC_PARAMRESET                  505
#define IDC_DISPEDGE0                   506
#define IDC_CHECK3                      507
#define IDC_INVEDGE0                    507
#define IDC_CHECK_COM1                  507
#define IDC_CHKEI3                      507
#define IDC_CHECK2_17                   507
#define IDC_SC                          507
#define IDC_TEXT_EDGECOL0               508
#define IDC_CHECK_COM2                  508
#define IDC_B_EDGECOL0                  509
#define IDC_CHECK_COM4                  509
#define IDC_EDGEWIDTH0                  510
#define IDC_CHECK_COM8                  510
#define IDC_B_EDGEWIDTH0                511
#define IDC_CHECK_COM16                 511
#define IDC_REFQUA                      512
#define IDC_CHECK_COM32                 512
#define IDC_MOANAME                     513
#define IDC_CHECK_COM64                 513
#define IDC_OW_SIG                      514
#define IDC_CHECK_COM128                514
#define IDC_OWSIGNAME                   515
#define IDC_CHECK_COM256                515
#define IDC_OW_MOA                      516
#define IDC_CHECK_COM17                 516
#define IDC_CHECK_COM512                516
#define IDC_OWMOANAME                   517
#define IDC_CHECK_NOFU                  518
#define IDC_CHECK_EV0IDLE               519
#define IDC_SYMRENEW                    520
#define IDC_REFEXTSIG                   521
#define IDC_EXTSIGNAME                  522
#define IDC_CHKEI1                      523
#define IDC_CHKEI2                      524
#define IDC_CHKBONE                     525
#define IDC_CAMROT                      526
#define IDC_CHECK2_0                    527
#define IDC_CHECK2_18                   528
#define IDC_CHECK2_19                   529
#define IDC_CHECK2_16                   530
#define IDC_CHECK2_20                   531
#define IDC_CHECK_COM_2_0               532
#define IDC_CHECK_COM_2_1               533
#define IDC_CHECK_COM_2_2               534
#define IDC_CHECK_COM_2_3               535
#define IDC_CHECK_COM_2_4               536
#define IDC_CHECK_COM_2_5               537
#define IDC_CHECK_COM_2_6               538
#define IDC_CHECK_COM_2_7               539
#define IDC_CHECK_COM_2_8               540
#define IDC_CHECK_COM_2_9               541
#define IDC_CHECK_COM_2_10              542
#define IDC_CHECK_COM_2_11              543
#define IDC_CHECK_COM_2_12              544
#define IDC_CHECK_COM_2_13              545
#define IDC_CHECK_COM_2_14              546
#define IDC_CHECK_COM_2_15              547
#define IDC_CHECK_COM_2_16              548
#define IDC_CHECK_COM_2_17              549
#define IDC_CHECK_COM_2_18              550
#define IDC_CHECK_COM_2_19              551
#define IDC_CHECK_COM_2_20              552
#define IDC_CHECK_COM_2_21              553
#define IDC_CHECK_COM_2_22              554
#define IDC_CHECK_COM_2_23              555
#define IDC_CHECK_COM_2_24              556
#define IDC_CHECK_COM_2_25              557
#define IDC_CHECK_COM_2_26              558
#define IDC_CHECK_COM_2_27              559
#define IDC_CHECK_COM_2_28              560
#define IDC_SYMLUMP                     561
#define IDC_MATNAME                     566
#define IDC_MATNO                       567
#define IDC_CHANGEMAT                   568
#define IDC_BUMPMAP                     569
#define IDC_REFBUMPMAP                  570
#define IDC_HMAP                        571
#define IDC_REFHMAP                     572
#define IDC_ROTZ                        573
#define IDC_ROTX                        574
#define IDC_ROTY                        575
#define IDC_APPLYROT                    576
#define IDC_LIMZ0                       577
#define IDC_LIMZ1                       578
#define IDC_LIMX0                       579
#define IDC_APPLYMV                     580
#define IDC_SCZ                         581
#define IDC_SCX                         582
#define IDC_SCY                         583
#define IDC_APPLYROT3                   584
#define IDC_APPLYSC                     584
#define IDC_LIMX1                       585
#define IDC_LIMY0                       586
#define IDC_LIMZ5                       587
#define IDC_LIMY1                       587
#define IDC_APPLYLIM                    588
#define IDC_FILENAME                    589
#define IDC_ALLYES                      590
#define IDC_ZA_ROT                      591
#define IDC_MKMNAME                     592
#define IDC_REFMKMNAME                  593
#define IDC_LIMZ2                       594
#define IDC_COMMONID                    594
#define IDC_ADDFORBID                   595
#define IDC_EVENTNO                     596
#define IDC_SETSYMM                     597
#define IDC_DARKRATE                    598
#define IDC_BUTTON7                     599
#define IDC_FRAMECOPYARI                599
#define IDC_APPLYVAL                    599
#define IDC_SETTING                     599
#define IDC_MOE                         599
#define IDC_ON_WA0                      600
#define IDC_RADIO_TEXONE                600
#define IDC_R_NES                       600
#define IDC_OPT_CUR                     600
#define IDC_TESTVAL0                    601
#define IDC_RADIO_TEXPALA               601
#define IDC_R_YES                       601
#define IDC_OPT_ALL                     601
#define IDC_ON_WA1                      602
#define IDC_RADIO_TEXGLOW               602
#define IDC_INF_NES                     602
#define IDC_OPT_FWD                     602
#define IDC_TESTVAL1                    603
#define IDC_RADIO_TEXGLOWALPHA          603
#define IDC_INF_YES                     603
#define IDC_OPT_SEL                     603
#define IDC_APPLYALPHATEST              604
#define IDC_RADIO_TEXMULTI              604
#define IDC_INF_NO                      604
#define IDC_CHECK_INVALID               605
#define IDC_MO_NES                      605
#define IDC_ZA1                         606
#define IDC_MO_YES                      606
#define IDC_ZA2                         607
#define IDC_MO_NO                       607
#define IDC_ZA3                         608
#define IDC_UNDO_NES                    608
#define IDC_COMBO_PLANE                 609
#define IDC_UNDO_YES                    609
#define IDC_FIXSIZE                     610
#define IDC_FIXX                        611
#define IDC_NOTCREATE                   612
#define IDC_CREATE0                     612
#define IDC_CREATE1                     613
#define IDC_GRAPH                       614
#define IDC_TATE                        615
#define IDC_YOKO                        616
#define IDC_DRAGX                       617
#define IDC_DRAGY                       618
#define IDC_DRAGX2                      619
#define IDC_DRAGZ                       619
#define IDC_DRAGVAL                     620
#define IDC_CHECK_NOTFU                 621
#define IDC_COMBO_SELDISP               622
#define IDC_BRUSHSIZE                   623
#define IDC_APPLYBRUSH                  624
#define IDC_DISPOBJNAME                 625
#define IDC_VERTNO                      626
#define IDC_INFVAL                      627
#define IDC_SL_VAL                      628
#define IDC_EDIT_VAL                    629
#define IDC_CHKJPOS                     630
#define IDC_GLOWMULT_R                  631
#define IDC_CREATEM                     632
#define IDC_CREATEP                     633
#define IDC_COLAMB                      634
#define IDC_COMBO_G                     635
#define IDC_COMBO_BONE                  636
#define IDC_TARX                        637
#define IDC_PX                          638
#define IDC_FRAMERANGE                  639
#define IDC_SPINRZ                      640
#define IDC_SPINROTZ                    640
#define IDC_COMBOPLANE                  641
#define IDC_COMBOONG                    642
#define IDC_SPINRY                      643
#define IDC_SPINRX2                     643
#define IDC_SPINROTX                    643
#define IDC_EVENT                       643
#define IDC_SPINRX                      644
#define IDC_SPINROTY                    644
#define IDC_COMBOKEY                    644
#define IDC_SPINDEG                     645
#define IDC_FULENG                      645
#define IDC_COMBOIDLE                   646
#define IDC_LIST                        647
#define IDC_NOTLIST                     648
#define IDC_SETLIST                     649
#define IDC_ADDSET                      650
#define IDC_SOUNDLIST                   651
#define IDC_REVERB                      652
#define IDC_BUFNUM                      653
#define IDC_EDIT5                       654
#define IDC_OGGDATANUM                  654
#define IDC_BGMREVERB                   655
#define IDC_BGMBUFNUM                   656
#define IDC_BGMOGGDATANUM               657
#define IDC_COMBOSOUND                  658
#define IDC_APPLYBGM                    659
#define IDC_SSLIST                      660
#define IDC_SSCOMBO                     660
#define IDC_BGMNAME                     661
#define IDC_SELIST                      662
#define IDC_SECOMBO                     662
#define IDC_BPM                         663
#define IDC_FPS                         664
#define IDC_FULLBONE                    665
#define IDC_START                       666
#define IDC_APPLYRANGE                  667
#define IDC_QUA                         668
#define IDC_SINGLEEVENT                 669
#define IDC_CONTINUE                    670
#define IDC_GOON                        670
#define IDC_NOTTOIDLE                   671
#define IDC_QUA2                        672
#define IDC_FILLUPUP                    672
#define IDC_SIG                         673
#define IDC_REFSIG                      674
#define IDC_GROUND                      675
#define IDC_REFGROUND                   676
#define IDC_MOA                         677
#define IDC_REFMOA                      678
#define IDC_CAMMODE                     679
#define IDC_REFGPA                      680
#define IDC_DEFAULT10                   680
#define IDC_BLD                         681
#define IDC_REFMOE                      682
#define IDC_REFSIG2                     683
#define IDC_REFBLD                      683
#define IDC_REFCAM                      684
#define IDC_SSF                         685
#define IDC_REFSSF                      686
#define IDC_SAF                         687
#define IDC_REFSSF2                     688
#define IDC_REFSAF                      688
#define IDC_CHKGPA                      689
#define IDC_CHKMOE                      690
#define IDC_INVISIBLE                   690
#define IDC_CHKCAM                      691
#define IDC_AXISKIND                    691
#define IDC_CHKSSF                      692
#define IDC_SLT0                        692
#define IDC_SLTS                        692
#define IDC_CHKGPA2                     693
#define IDC_CHKSAF                      693
#define IDC_EDITT0                      693
#define IDC_EDITTS                      693
#define IDC_T0                          694
#define IDC_TS                          694
#define IDC_SLT1                        695
#define IDC_SLD0                        695
#define IDC_SLDS                        695
#define IDC_EDITMAX0                    696
#define IDC_EDITMAXS                    696
#define IDC_MAX0                        697
#define IDC_MAXS                        697
#define IDC_EDITD0                      698
#define IDC_EDITDS                      698
#define IDC_D0                          699
#define IDC_DS                          699
#define IDC_SYNC                        700
#define IDC_MKIND                       701
#define IDC_ALLBONE                     702
#define IDC_MINTS                       702
#define IDC_ONEBONE                     703
#define IDC_MAXTS                       703
#define IDC_CTRL                        704
#define IDC_EDITTS2                     704
#define IDC_EDITTE                      704
#define IDC_EDITMINTS                   705
#define IDC_EDITMAXTS                   706
#define IDC_TS2                         707
#define IDC_TE                          707
#define IDC_SLT2                        708
#define IDC_SLTE                        708
#define IDC_EDITMINTE                   709
#define IDC_MINTE                       710
#define IDC_SLT3                        711
#define IDC_SLDE                        711
#define IDC_EDITMAX1                    712
#define IDC_EDITMAXE                    712
#define IDC_MAX1                        713
#define IDC_MAXE                        713
#define IDC_EDITD1                      714
#define IDC_EDITDE                      714
#define IDC_D1                          715
#define IDC_DE                          715
#define IDC_EDITMAXTE                   716
#define IDC_MAXTS2                      717
#define IDC_MAXTE                       717
#define IDC_LOCK                        718
#define IDC_ROT                         719
#define IDC_CALCSP                      720
#define IDC_CHKHEN                      721
#define IDC_DRAG                        722
#define IDC_BUTTON10                    723
#define IDC_APPLYMOVE                   723
#define IDC_OPTARGET                    723
#define IDC_CHUCHU                      723
#define IDC_APPLYDRAG                   724
#define IDC_CHKDS                       725
#define IDC_TOPOFJOINT                  726
#define IDC_TORSO                       727
#define IDC_LEFTHIP                     728
#define IDC_LEFTKNEE                    729
#define IDC_LEFTFOOT                    730
#define IDC_KSTNAME                     731
#define IDC_REFKST                      732
#define IDC_RIGHTHIP                    733
#define IDC_SETCHKDLG                   733
#define IDC_RIGHTKNEE                   734
#define IDC_RIGHTFOOT                   735
#define IDC_NECK                        736
#define IDC_HEAD                        737
#define IDC_LEFTSHOULDER                738
#define IDC_SOUTAI                      738
#define IDC_LEFTELBOW                   739
#define IDC_BUTTON12                    739
#define IDC_ZETTAI                      739
#define IDC_LEFTHAND                    740
#define IDC_CURFRAME                    740
#define IDC_RIGHTSHOULDER               741
#define IDC_SELSTART                    741
#define IDC_RIGHTELBOW                  742
#define IDC_CHKFIRST                    742
#define IDC_LEFTHAND2                   743
#define IDC_RIGHTHAND                   743
#define IDC_FIRSTFRAME                  743
#define IDC_LASTFRAME                   744
#define IDC_STEP                        744
#define IDC_KSTIN                       744
#define IDC_RANGESTART                  745
#define IDC_REFKSTIN                    745
#define IDC_APPLYSTART                  746
#define IDC_BUTTON13                    747
#define IDC_NCRE                        748
#define IDC_CHKTOPOFJOINT               749
#define IDC_CHKTORSO                    750
#define IDC_CHKKINECT                   750
#define IDC_CHKLEFTHIP                  751
#define IDC_FILTERTYPE                  751
#define IDC_CHKLEFTNKEE                 752
#define IDC_CHKLEFTKNEE                 752
#define IDC_CHKMORPH                    752
#define IDC_CHKLEFTFOOT                 753
#define IDC_FRAMES                      753
#define IDC_CHKRIGHTHIP                 754
#define IDC_WHESCALE                    754
#define IDC_CHKRIGHTNKEE                755
#define IDC_CHKRIGHTKNEE                755
#define IDC_JOINTROT                    755
#define IDC_CHKRIGHTFOOT                756
#define IDC_CHKCHUCHU                   756
#define IDC_CHKNECK                     757
#define IDC_MULTIFRAME                  757
#define IDC_CHKHEAD                     758
#define IDC_BUTTON11                    758
#define IDC_IKTDISP                     758
#define IDC_CHKLEFTSHOULDER             759
#define IDC_MULTX                       759
#define IDC_CHKLEFTELBOW                760
#define IDC_MULTY                       760
#define IDC_ZEROV                       760
#define IDC_CHKLEFTHAND                 761
#define IDC_MULTX3                      761
#define IDC_MULTZ                       761
#define IDC_CHKRIGHTSHOULDER            762
#define IDC_FBXNAME                     762
#define IDC_CHKRIGHTELBOW               763
#define IDC_REGISTKEY                   763
#define IDC_CHKRIGHTHAND                764
#define ID_RMENU_LEVEL1                 900
#define ID_RMENU_LEVEL2                 901
#define ID_RMENU_LEVEL3                 902
#define ID_RMENU_LEVEL4                 903
#define ID_RMENU_LEVEL5                 904
#define ID_RMENU_LEVEL6                 905
#define ID_RMENU_LEVEL7                 906
#define ID_RMENU_LEVEL8                 907
#define ID_RMENU_LEVEL9                 908
#define ID_RMENU_LEVEL10                909
#define ID_RMENU_LEVEL11                910
#define ID_RMENU_LEVEL12                911
#define ID_RMENU_LEVEL13                912
#define ID_RMENU_LEVEL14                913
#define ID_RMENU_LEVEL15                914
#define ID_RMENU_LEVELINF               915
#define ID_RMENU_IKMODE                 916
#define ID_RMENU_IKLEVEL                917
#define ID_RMENU_MODE_JOINT             918
#define ID_RMENU_MODE_OPE               919
#define ID_RMENU_SIGPARAMS              920
#define ID_RMENU_IKTRANS                921
#define ID_RMENU_IKSKIP                 922
#define ID_RMENU_BONEMARK               923
#define ID_RMENU_COPY                   924
#define ID_RMENU_IKDRAG                 925
#define ID_RMENU_FKDRAG                 926
#define ID_RMENU_IKTARGET               927
#define ID_RMENU_SYMX                   928
#define ID_RMENU_SYMY                   929
#define ID_RMENU_SYMZ                   930
#define ID_RMENU_BONEPROP               931
#define IDC_RADIO_ONESKIN0              1000
#define IDC_RADIO_ONESKIN1              1001
#define IDC_RADIO_NOSKIN0               1002
#define IDC_RADIO_DIRECT0               1003
#define IDC_RADIO_SYM                   1004
#define IDC_RADIO_SETINF                1100
#define IDC_RADIO_BONE                  1101
#define IDC_RADIO_DISPBONE              1110
#define IDC_RADIO_DISPSYM               1111
#define IDM_CTRLX                       12770
#define IDM_CTRLZ                       12772
#define IDM_CTRLJ                       12773
#define IDM_CTRLC                       12774
#define IDM_CTRLV                       12775
#define IDM_HOME                        12776
#define IDM_END                         12777
#define IDM_PRIOR                       12778
#define IDM_NEXT                        12779
#define IDM_PAUSE                       12781
#define IDMENU_READ_ACT                 32769
#define IDMENU_WRITE_ACT                32771
#define IDMENU_TREEEDIT                 32772
#define IDMENU_MOTEDIT                  32773
#define IDMENU_READ_SIG                 32775
#define IDMENU_READ_ROK                 32776
#define IDMENU_CAMERA                   32778
#define IDMENU_OPTION                   32779
#define IDMENU_IMPORTSIG                32781
#define IDMENU_IMPORTROK                32782
#define IDMENU_SHDPARAM                 32783
#define IDM_CTRLB                       32783
#define IDMENU_JOINTLOC                 32784
#define IDMENU_NEWJOINT                 32785
#define IDM_GDISP                       32785
#define IDMENU_INFLUENCE                32787
#define ID_RMENU_32787                  32787
#define IDMENU_BG                       32788
#define IDMENU_LIGHT                    32789
#define ID_ACCELERATOR32791             32791
#define IDM_ZOOM                        32791
#define ID_32793                        32793
#define IDMENU_JOINTDEL                 32795
#define IDMENU_CONV2SCOPE               32797
#define IDM_CTRLUP                      32798
#define IDM_CTRLDOWN                    32799
#define ID_RMENU_32801                  32801
#define ID_32802                        32802
#define ID_Menu                         32803
#define ID_MCRMENU_32805                32805
#define ID_MCRMENU_ADD                  32806
#define ID_MCRMENU_                     32807
#define ID_MCRMENU_DEL                  32808
#define ID_MCRMENU_PROP                 32809
#define IDM_OVERWRITE                   32810
#define ID_FILE_SIG32812                32812
#define IDM_UP                          32813
#define IDM_DOWN                        32814
#define IDM_RIGHT                       32815
#define IDM_LEFT                        32816
#define IDM_IKTON                       32823
#define IDM_IKTOFF                      32824
#define IDM_IKTTOGGLE                   32824
#define IDM_IKTTOGLE                    32824
#define IDM_CTRLI                       32826
#define IDM_CTRLO                       32829
#define IDM_CTRLN                       32830
#define IDM_CTRL_YAUP                   32832
#define IDM_CTRL_YADOWN                 32833
#define IDM_SHIFT_UP                    32835
#define IDM_SHIFT_DOWN                  32836
#define IDM_SHIFT_LEFT                  32837
#define IDM_SHIFT_RIGHT                 32838
#define IDM_TARGET_UP                   32840
#define IDM_TARGET_DOWN                 32841
#define IDM_TARGET_LEFT                 32842
#define IDM_TARGET_RIGHT                32843
#define ID_32847                        32847
#define ID_GPA_32848                    32848
#define ID_MOE_32849                    32849
#define IDM_G_LEFT                      32853
#define IDM_G_RIGHT                     32854
#define ID_MCRMENU_COPY                 32855
#define ID_MCRMENU_PASTE                32856
#define ID_32867                        32867
#define IDM_CTRLSHIFTT                  32874
#define IDM_ALT_R                       32876
#define IDM_ALT_S                       32877
#define IDM_ALT_T                       32878
#define IDM_BAKEMOTION                  32880
#define IDM_CTRLT                       35000
#define IDMENU_READ_MQO                 50000
#define IDMENU_IMPORTMQO                50001
#define ID_MENU_PLUGIN                  55000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        354
#define _APS_NEXT_COMMAND_VALUE         32881
#define _APS_NEXT_CONTROL_VALUE         764
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
