//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RokDeBone2.rc
//
#define ID_FILE_LOAD_BF                 0
#define IDS_PROJNAME                    100
#define IDR_ROKDEBONE2                  101
#define IDS_TB_R                        101
#define IDB_SIGTREEVIEW2                102
#define IDS_TB_T                        102
#define IDR_SIGTREEVIEW2                103
#define IDS_TB_S                        103
#define IDD_SIGEDITDLG                  104
#define IDS_TB_G                        104
#define IDD_OPTDLG                      105
#define IDS_TB_L                        105
#define IDD_MOTPARAMDLG                 106
#define IDS_TB_T2                       106
#define IDB_SIGTREEVIEW                 107
#define IDS_TB_J                        107
#define IDR_SIGTREEVIEW                 108
#define IDS_TB_FACE                     108
#define IDD_SHDPARAMDLG                 109
#define IDS_TB_LINE                     109
#define IDD_LOADPARAMDLG                110
#define IDS_TB_ZA1                      110
#define IDD_FRAMEOPEDLG                 111
#define IDS_TB_ZA2                      111
#define IDD_MOTSETTINGDLG               112
#define IDD_JOINTLOCDLG                 113
#define IDD_NEWJOINTDLG                 114
#define IDD_WRITEBMPDLG                 115
#define IDD_INFLUENCEDLG                116
#define IDD_BGDLG                       117
#define IDD_LIGHTDLG                    118
#define IDD_VERSIONDLG                  119
#define IDC_SP_UD                       201
#define IDMENU_IKUNDO                   201
#define IDC_SP_ROT                      202
#define IDD_CAMERADLG                   202
#define IDC_SELLOCK_START               202
#define IDC_UD_RESET                    203
#define IDB_PART_IMAGE                  203
#define IDC_SELLOCK_STOP                203
#define IDC_SP_ZOOM                     204
#define IDB_PART_SELECT                 204
#define IDC_SP_TWIST                    204
#define IDC_ROT_RESET                   205
#define IDB_DISP_IMAGE                  205
#define IDC_SELLOCK_NAME                205
#define IDC_ZOOM_RESET                  206
#define IDB_DISP_SELECT                 206
#define IDC_SP_BONENUM                  206
#define IDC_RADIO_BONE1                 207
#define IDB_BONE_IMAGE                  207
#define IDC_SP_RAD2                     207
#define IDC_TEX_BONENUM                 207
#define IDC_RADIO_BONE2                 208
#define IDB_BONE_SELECT                 208
#define IDC_RAD2_RESET                  208
#define IDC_RESET_ROT                   208
#define IDC_RESET_MV                    209
#define IDC_TREE_MOT                    210
#define IDR_DUMMYMENU                   210
#define IDD_MQODLG                      210
#define IDR_DLGMENU                     211
#define IDD_DISPSWITCHDLG               211
#define IDC_SL_MP                       212
#define IDC_EDIT_MULT                   212
#define IDMENU_REVIKUNDO                212
#define IDC_DELETE                      213
#define IDD_TEXSETTINGDLG               213
#define IDC_ADD                         214
#define IDD_LDSIG                       214
#define IDC_FRAMEPASTE                  215
#define IDC_ADD2                        215
#define IDD_WRITEBFDLG                  215
#define IDC_FRAMECOPY                   216
#define IDC_DELETE2                     216
#define IDD_FRAMECOPYDLG                216
#define IDC_PREVIEW                     217
#define IDD_PASTETYPEDLG                217
#define IDC_SL_ROTX                     218
#define IDC_SL_ROTY                     219
#define IDC_SP_ROTRAD                   219
#define IDI_ICON1                       219
#define IDC_SL_ROTZ                     220
#define IDC_SP_ROTX                     221
#define IDD_PARSDLG                     221
#define IDC_SP_ROTY                     222
#define ID_222                          222
#define IDC_SP_ROTZ                     223
#define IDD_AXISDLG                     223
#define IDC_MVX                         224
#define IDC_TEX_RAD                     224
#define IDD_MOTDLG                      224
#define IDC_MVY                         225
#define IDC_RADIO_SQUAD                 225
#define IDD_VIKDLG                      225
#define IDC_MVZ                         226
#define IDC_RADIO_SLERP                 226
#define IDC_MV_SET                      227
#define IDC_STATIC1                     228
#define IDC_CHECK_SKINNING              228
#define IDC_SWITCH13                    228
#define IDC_UNSELCOL                    228
#define IDC_STATIC2                     229
#define IDC_ALL_NOSKINNING              229
#define IDC_TEX_ROTX                    230
#define IDC_ALL_SKINNING                230
#define IDC_STATIC3                     231
#define IDC_DISPSWITCHNO                231
#define IDC_TEX_ROTY                    232
#define IDC_COMBO_NO                    232
#define IDC_STATIC4                     233
#define IDC_SWITCHON                    233
#define IDC_TEX_ROTZ                    234
#define IDC_SWITCHOFF                   234
#define IDC_STATIC5                     235
#define IDC_FRAMENO                     235
#define IDC_STATIC6                     236
#define IDC_SWITCH1                     236
#define IDC_STATIC7                     237
#define IDC_SWITCH2                     237
#define IDC_STATIC8                     238
#define IDC_SWITCH3                     238
#define IDC_STATIC9                     239
#define IDC_SWITCH4                     239
#define IDC_TEX_NAME                    240
#define IDC_SWITCH5                     240
#define IDC_TEX_CURRENT                 241
#define IDC_SWITCH6                     241
#define IDC_SWITCH7                     242
#define IDC_MP                          243
#define IDC_SWITCH8                     243
#define IDR_R_MENU                      243
#define IDC_SHDNAME                     244
#define IDC_SWITCH9                     244
#define IDC_SERIALNO                    245
#define IDC_SWITCH10                    245
#define IDC_SHDTYPE                     246
#define IDC_SWITCH11                    246
#define IDC_DEPTH                       247
#define IDC_SWITCH12                    247
#define ID_RMENU_247                    247
#define IDC_CLOCKWISE                   248
#define IDC_SWITCH14                    248
#define IDC_ALPHA                       249
#define IDC_SWITCH15                    249
#define ID_RMENU_249                    249
#define IDC_TEXNAME                     250
#define IDC_DISPSWITCH                  250
#define IDC_TEXREF                      251
#define IDC_NAME_ADD                    251
#define IDD_BONELINEDLG                 251
#define IDC_TRANSPARENT                 252
#define IDC_NAME_DEL                    252
#define IDR_ACCELERATOR1                252
#define IDC_NAME_UP                     253
#define IDD_WRITEMQODLG                 253
#define IDC_TEXRULE                     254
#define IDC_NAME_DOWN                   254
#define IDC_TEXREPX                     255
#define IDC_COMBO_TEXRULE               255
#define IDB_BITMAP1                     255
#define IDC_TEXREPY                     256
#define IDC_TEXREPU                     256
#define IDB_BITMAP2                     256
#define IDC_UANIME                      257
#define IDC_TEXREPV                     257
#define IDD_LDBVH                       257
#define IDC_VANIME                      258
#define IDC_UANIM                       258
#define IDD_WRITEIM2Dlg                 258
#define IDC_REF_DIFFUSE                 259
#define IDC_VANIM                       259
#define IDC_DISP_DIFFUSE                260
#define IDD_DIALOG1                     260
#define IDD_MIKOBLENDDLG                260
#define IDC_RADIO_POLY1                 261
#define IDC_TEXTURE                     261
#define IDD_DIALOG2                     261
#define IDD_LOADNAMEDLG                 261
#define IDC_RADIO_POLY2                 262
#define IDC_COMBO_ANIM_REP              262
#define IDD_LDSIG1                      262
#define IDD_LDGROUNDDLG                 262
#define IDC_REF_AMBIENT                 263
#define IDC_ANIM_STEP                   263
#define IDB_BITMAP3                     263
#define IDC_SL_SPECULAR                 264
#define IDC_RADIO_NORMAL                264
#define IDB_BITMAP4                     264
#define IDC_TEX_DIFFUSE                 265
#define IDC_RADIO_ANIM                  265
#define IDB_BITMAP5                     265
#define IDC_TEX_AMBIENT                 266
#define IDC_RADIO_MULTI                 266
#define IDB_TB8                         266
#define IDC_DISP_AMBIENT                267
#define IDC_LIST_TEXNAME                267
#define IDC_TEX_SPECULAR                268
#define IDC_NOTUSE                      269
#define IDC_MULTIPLE                    270
#define IDC_RADIO_FULLPATH              270
#define IDC_SWAPXZ                      271
#define IDC_RADIO_ONLYNAME              271
#define IDC_CENTERX                     272
#define IDC_SIGNAME                     272
#define IDC_CENTERZ                     273
#define IDC_REF                         273
#define IDC_DIV_COLOR                   274
#define IDC_MULT                        274
#define IDC_DIV_GROUP                   275
#define IDC_RADIO_NOALPHA               275
#define IDC_INVZ                        276
#define IDC_RADIO_WITHALPHA             276
#define IDC_FRAMEDEL                    277
#define IDC_RADIO_WITHTRANS             277
#define IDC_PARAMSET                    278
#define IDC_TEXT                        279
#define IDC_CHECK1                      279
#define IDC_LIST1                       280
#define IDC_LIST2                       281
#define IDC_CHKINV                      282
#define IDC_TEXT_EYEY                   283
#define IDC_TEXT_RAD                    284
#define IDC_SLIDER1                     284
#define IDC_TEXT_DIST                   285
#define IDC_FOVTEXT                     285
#define IDC_TEXT_RAD2                   286
#define IDC_RADIO_PARS1                 286
#define IDC_RADIO_ORTHO1                287
#define IDC_RADIO_GROUND1               288
#define IDC_EDIT_ORTHOSIZE              289
#define IDC_RADIO_GROUND2               290
#define IDC_RANGEX                      291
#define IDC_RANGEY                      292
#define IDC_SL_SIZE                     292
#define IDC_RANGEZ                      293
#define IDC_TEXT_SIZE                   293
#define IDC_TOTALFRAME                  294
#define IDC_RADIO_UNDO1                 294
#define IDC_RADIO1                      295
#define IDC_RADIO_UNDO0                 295
#define IDC_RADIO2                      296
#define IDC_BONEDISP                    296
#define IDC_VIEW                        297
#define IDC_RADIO3                      298
#define IDC_SL_XZ                       298
#define IDC_NAME                        299
#define IDC_SL_Y                        299
#define IDC_TEXT_STATUS                 300
#define IDC_TEXT_SL_XZ                  300
#define IDC_TEXT_TARGET                 301
#define IDC_TEXT_SL_Y                   301
#define IDC_SP_TARGET                   302
#define IDC_RADIO_VERT                  302
#define IDC_TARGET_RESET                303
#define IDC_RADIO_CUSTOM                303
#define IDC_SP_MP                       304
#define IDC_RADIO_CROSS                 304
#define IDC_STOP                        305
#define IDC_TAB1                        305
#define IDC_ALLDELETE                   306
#define IDC_TEXT_SELNAME                306
#define IDC_EDITX                       307
#define IDC_ALLDELETE2                  307
#define IDC_TEXT_CURX                   307
#define IDC_EDITY                       308
#define IDC_TEXT_CURY                   308
#define IDC_EDITZ                       309
#define IDC_TEXT_CURZ                   309
#define IDC_APPLY                       310
#define IDC_EDIT_DIV                    310
#define IDC_TEXT_NAME                   311
#define IDC_EDIT_TX                     311
#define IDC_EDIT_NUM                    312
#define IDC_EDIT_TY                     312
#define IDC_PREFIX                      313
#define IDC_EDIT_TZ                     313
#define IDC_STARTFRAME                  314
#define IDC_START_IK                    314
#define IDC_ENDFRAME                    315
#define IDC_STOP_IK                     315
#define IDC_START_SHIFTIK               316
#define IDC_NOTRANSIK                   317
#define IDC_TREE1                       320
#define IDC_RADIO_BM_ON                 320
#define IDC_NAME1                       321
#define IDC_RADIO_BM_OFF                321
#define IDC_REF1                        322
#define IDC_IKSKIP                      322
#define IDC_NAME2                       323
#define IDC_RESET_SC                    323
#define IDC_REF2                        324
#define IDC_RADIO_MODEJOINT             324
#define IDC_MVU                         325
#define IDC_RADIO_MODEOPE               325
#define IDC_MVV                         326
#define IDC_COMBO1                      326
#define IDC_COMBO_LEVEL                 326
#define IDC_COMBO_FPS                   326
#define IDC_REF_SELCOL                  327
#define IDC_COLORREF                    328
#define IDC_REF_UNSELCOL                328
#define IDC_COLOR                       329
#define IDC_SELCOL                      329
#define IDC_NUMPRIM                     330
#define IDC_RADIO_NOTDISP               330
#define IDC_SL_ALPHA                    331
#define IDC_RADIO                       331
#define IDC_RADIO_DODISP                331
#define IDC_SL_BETA                     332
#define IDC_CHECK_CHILD                 332
#define IDC_TEXT_ALPHA                  333
#define IDC_TEXT_BETA                   334
#define IDC_SAVE_F5                     334
#define IDC_TEXT_VEC                    335
#define IDC_SAVE_F6                     335
#define IDC_SAVE_F7                     336
#define IDC_BUTTON5                     337
#define IDC_SAVE_F8                     337
#define IDC_EDIT_HEAD                   338
#define IDC_BUTTON1                     339
#define IDC_REF_HEAD                    339
#define IDC_REF_BVH                     339
#define IDC_REF_IM2                     339
#define IDC_NEXTMP                      339
#define IDC_BEFORE_MP                   339
#define IDC_RADIO_ALL                   340
#define IDC_RADIO_KEY                   341
#define IDC_EDIT1                       342
#define IDC_EDIT_BVH                    342
#define IDC_EDIT_BONEFILE               342
#define IDC_EDIT_IM2NAME                342
#define IDC_EDIT_MOTJUMP                342
#define IDC_CHECK_MOTONLY               343
#define IDC_EDIT_MQONAME                344
#define IDC_REF_MQONAME                 345
#define IDC_EDIT_BONNAME                346
#define IDC_REF_BONNAME                 347
#define IDC_EDIT2                       348
#define IDC_CHECK_OUTBONE               349
#define IDC_CHECK_OUTBF                 350
#define IDC_BUTTON2                     351
#define IDC_REF_BONEFILE                351
#define IDC_NEXT_MP                     351
#define IDC_RADIO_FORSIG                352
#define IDC_RADIO_FORMQO                353
#define IDC_RADIO_RDB2                  354
#define IDC_RADIO_MIKO                  355
#define IDC_RADIO_FPS60                 356
#define IDC_RADIO_FPS30                 357
#define IDC_RADIO_SKINNING              358
#define IDC_RADIO_MIX                   359
#define IDC_COMBO2                      360
#define IDC_COMBO_MOTSTEP               360
#define IDC_TEXT_COL                    361
#define IDC_QUANAME                     362
#define IDC_IM2NAME                     363
#define IDC_BONNAME                     364
#define IDC_RADIO_FK                    365
#define IDC_RADIO_IK                    366
#define IDC_RADIO_MOTSTOP               367
#define IDC_RADIO_MOTREP                368
#define IDC_RADIO_MOTINV                369
#define IDC_RADIO_MOTJUMP               370
#define IDM_CTRLX                       12770
#define IDM_CTRLZ                       12772
#define IDM_CTRLJ                       12773
#define IDM_CTRLC                       12774
#define IDM_CTRLV                       12775
#define IDM_HOME                        12776
#define IDM_END                         12777
#define IDM_PRIOR                       12778
#define IDM_NEXT                        12779
#define IDM_PAUSE                       12781
#define IDMENU_READ_ACT                 32769
#define IDMENU_WRITE_ACT                32771
#define IDMENU_TREEEDIT                 32772
#define IDMENU_MOTEDIT                  32773
#define IDMENU_READ_SIG                 32775
#define IDMENU_READ_ROK                 32776
#define IDMENU_WRITE_SIG                32777
#define IDMENU_CAMERA                   32778
#define IDMENU_OPTION                   32779
#define IDMENU_IMPORTSIG                32781
#define IDMENU_IMPORTROK                32782
#define IDMENU_SHDPARAM                 32783
#define IDM_CTRLB                       32783
#define IDMENU_JOINTLOC                 32784
#define IDMENU_NEWJOINT                 32785
#define IDM_GDISP                       32785
#define IDMENU_WRITE_BMP                32786
#define IDMENU_INFLUENCE                32787
#define ID_RMENU_32787                  32787
#define IDMENU_BG                       32788
#define IDMENU_LIGHT                    32789
#define IDMENU_READ_MQO                 50000
#define IDMENU_IMPORTMQO                50001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        267
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         370
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
